#apiVersion: rbac.authorization.k8s.io/v1beta1
---
#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus-server
      sla: kind
  template:
    metadata:
      labels:
        app: prometheus-server
        team: backend-devops
        sla: kind
    spec:
      containers:
        - name: prometheus
          #image: prom/prometheus:v2.20.1
          image: prom/prometheus:v2.30.3
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--storage.tsdb.retention.time=30d"     
            - "--storage.tsdb.retention.size=110GB"
            - "--web.enable-admin-api"
            - "--web.enable-lifecycle"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
          resources:
            # limits:
            #   memory: "9500Mi"
            #   cpu: "1500m"
            requests: 
              memory: "500Mi"
              cpu: "200m"
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: prometheus-server
    team: backend-devops
    sla: kind
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090 